In [18]:
import numpy as np

# Task no 1
def function1():
    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
    x =  np.arange(1,13).reshape((6,2)) 

    return x

In [19]:
function1()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [20]:
# Task2
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
    
    x = np.arange(10,37,dtype=np.float64).reshape((3,3,3))     #wrtie your code here


    return x

In [21]:
function2()

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [58]:
#task3
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    x = a[(a % 5 == 0) & (a %  7== 0)] #wrtie your code here
    return x

In [59]:
function3()

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [24]:
#task4
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
    print(arr)
    return arr[:,[1,0,2]]#wrtie your code here
    """
    Expected Output:
          array([[1, 0, 2],
                [4, 3, 5],
                [7, 6, 8]])
    """ 

In [25]:
function4()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [26]:
#task5
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
   
    z = np.zeros((4,5),dtype=np.int8)#wrtie your code here
  
    return z
    """
    Expected Output:
          array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0]])
    """ 


In [27]:
function5()

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [28]:

#task6
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
    arr = np.zeros(10,dtype=np.int8)#wrtie your code here
    print("Update 5th and 8th value to 10,20")
    arr[4] = 10
    arr[7] = 20
    return arr
   

In [29]:
function6()

Update 5th and 8th value to 10,20


array([ 0,  0,  0,  0, 10,  0,  0, 20,  0,  0], dtype=int8)

In [30]:
    
#task7
def function7():
        #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    arr = np.arange(4,dtype=np.int8)    
    arr[:] = 0
    return arr#write your code here

    """
    Expected Output:
          array([0, 0, 0, 0], dtype=int64)
    """ 

IndentationError: expected an indented block (<ipython-input-30-5d817290924e>, line 5)

In [31]:
function7()

NameError: name 'function7' is not defined

In [32]:
#task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x = np.arange(10).reshape(2,5)#write your code here
    x[:]=6
    return x

"""
     Expected Output:
              array([[6, 6, 6, 6, 6],
                     [6, 6, 6, 6, 6]], dtype=uint32)
     """ 

'\n     Expected Output:\n              array([[6, 6, 6, 6, 6],\n                     [6, 6, 6, 6, 6]], dtype=uint32)\n     '

In [33]:
function8()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [34]:
#task9
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a = []# write your code here
    for i in range(100):
        if i%2==0:
            a.append(str(i))
    return a

"""
     Expected Output:
              array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
                    28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
                    54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
                    80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])
     """ 

'\n     Expected Output:\n              array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,\n                    28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,\n                    54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,\n                    80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])\n     '

In [35]:
function9()

['0',
 '2',
 '4',
 '6',
 '8',
 '10',
 '12',
 '14',
 '16',
 '18',
 '20',
 '22',
 '24',
 '26',
 '28',
 '30',
 '32',
 '34',
 '36',
 '38',
 '40',
 '42',
 '44',
 '46',
 '48',
 '50',
 '52',
 '54',
 '56',
 '58',
 '60',
 '62',
 '64',
 '66',
 '68',
 '70',
 '72',
 '74',
 '76',
 '78',
 '80',
 '82',
 '84',
 '86',
 '88',
 '90',
 '92',
 '94',
 '96',
 '98']

In [36]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = arr - brr[:,None]# write your code here 
  
    return subt

"""
     Expected Output:
               array([[2 2 2]
                      [2 2 2]
                      [2 2 2]])
     """ 
    

'\n     Expected Output:\n               array([[2 2 2]\n                      [2 2 2]\n                      [2 2 2]])\n     '

In [37]:
function10()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [38]:
    
#task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = arr[arr % 2 == 0] = -1 
# array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])#write your code here 
  
    return ans

"""
     Expected Output:
              array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
     """ 
   

IndentationError: expected an indented block (<ipython-input-38-288ee97cebfa>, line 5)

In [39]:
function11()

NameError: name 'function11' is not defined

In [60]:
    
#task12
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    arr = np.array([1,2,3])
    ans = np.r_[np.repeat(arr,3),np.tile(arr,3)]#write your code here 
  
    return ans

"""
     Expected Output:
              array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
     """ 


IndentationError: expected an indented block (<ipython-input-60-29c5cc4658d0>, line 6)

In [41]:
function12()

NameError: name 'function12' is not defined

In [42]:

#task13
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = arr[(arr>=5) & (arr<=10)]#write your code here 
  
    return ans

    """
     Expected Output:
              array([6, 9])
     """ 


In [43]:
function13()

array([ 6,  9, 10])

In [45]:

#task14
def function14():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    
    
    arr = np.arange(10, 34, 1).reshape(8,3) #write reshape code
    #ans = #write your code here 
  
    return arr

    """
     Expected Output:
       [array([[10, 11, 12],[13, 14, 15]]), 
        array([[16, 17, 18],[19, 20, 21]]), 
        array([[22, 23, 24],[25, 26, 27]]), 
        array([[28, 29, 30],[31, 32, 33]])]
     """ 

In [46]:
function14()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [50]:
    
#task15
def function15():
    #Sort following NumPy array by the second column
    arr = np.array([[ 8,  2, -2],
                    [-4,  1,  7],
                    [ 6,  3,  9]])
    ans = arr[[1,0,2],]#write your code here 
  
    return ans

    """
     Expected Output:
           array([[-4,  1,  7],
                   [ 8,  2, -2],
                   [ 6,  3,  9]])
     """ 

IndentationError: expected an indented block (<ipython-input-50-57e13264029a>, line 5)

In [51]:
function15()

NameError: name 'function15' is not defined

In [55]:
#task16
def function16():
    #Write a NumPy program to join a sequence of arrays along depth.
    
    
    x = np.array([[1], [2], [3]])
    y = np.array([[2], [3], [4]])
    ans = np.concatenate((x,y)#write your code here 
  
    return ans

    """
     Expected Output:
                [[[1 2]]
                 [[2 3]]
                 [[3 4]]]
     """ 
    

SyntaxError: invalid syntax (<ipython-input-55-83dcd17d524a>, line 10)

In [54]:
function16()

TypeError: only integer scalar arrays can be converted to a scalar index

In [65]:
#Task17
def function17():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))
    arr = np.where((arr%3==0) & (arr%5==0),"YES","NO")
    return arr          # Write Your Code HERE

#Excpected Out
"""
array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')
"""


"\narray([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],\n       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],\n       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],\n       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],\n       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],\n       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],\n       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],\n       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],\n       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],\n       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],\n      dtype='<U3')\n"

In [66]:
function17()

array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')

In [67]:

#Task18
def function18():
    # count values of "students" are exist in "piaic"
    piaic = np.arange(100)
    students = np.array([5,20,50,200,301,7001])
    x = np.count_nonzero(students<101)# Write you code Here
    return x

    #Expected output: 3

In [69]:
function18()

3

In [70]:
# Task19
def function19():
    #Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:

    X = np.arange(1, 26).reshape((5, 5))              # Write your code here
    W = X.copy().transpose()                # Write your code here 
    b = 5               # Write your code here
    output = (X*W)+5          # Write your code here
    return output
    #expected output
    """
    array([[  6,  17,  38,  69, 110],
       [ 17,  54, 101, 158, 225],
       [ 38, 101, 174, 257, 350],
       [ 69, 158, 257, 366, 485],
       [110, 225, 350, 485, 630]])
    """


In [71]:
function19()

array([[  6,  17,  38,  69, 110],
       [ 17,  54, 101, 158, 225],
       [ 38, 101, 174, 257, 350],
       [ 69, 158, 257, 366, 485],
       [110, 225, 350, 485, 630]])

In [74]:

#Task20
def function20():
    #apply fuction "abc" on each value of Array "X"
    def function():
        x = np.arange(1,11)
        def abc(x):
            x = x*2+3-2
            return x
    
        return abc(x)

    function()
#Expected Output: array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [75]:
function20()